version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../fem:/app/fem
      - ../raytracer:/app/raytracer
      - ../examples:/app/examples
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - acoustic-net
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - acoustic-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - acoustic-net
    restart: unless-stopped

  # Optional: Jupyter notebook for development and analysis
  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/app/notebooks
      - ../examples:/app/examples
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: ["conda", "run", "-n", "acoustic-sim", "jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    networks:
      - acoustic-net
    profiles:
      - dev

volumes:
  redis_data:

networks:
  acoustic-net:
    driver: bridge
